### ISSUE TITLE
環境をDockerにする

### ISSUE THREAD

**Issue by Takumi-Nozaki** [Takumi-Nozaki/Songsheet-app#10]

**Comment by iwaseasahi** [comment]
こちら自分の方でやります。
これをやることによって、自分の mac でも Songsheet-app の環境を作りやすくなるので。

**Comment by iwaseasahi** [comment]
https://www.sqlite.org/index.html

**Comment by iwaseasahi** [comment]
docker 内で sqlite3 に接続できた様子。

```
sqlite> .open db/development.sqlite3
sqlite> .database
main: /usr/src/app/db/development.sqlite3 r/w
sqlite> .open db/test.sqlite3
sqlite> .database
main: /usr/src/app/db/test.sqlite3 r/w
```

**Comment by iwaseasahi** [comment]
sqlite は以下で接続を閉じます。

```
sqlite> .quit
```

**Comment by iwaseasahi** [comment]
事前に以下をやっておく必要あり。

```
$ docker-compose run --rm app rails webpacker:install
```

**Comment by iwaseasahi** [comment]
Docker 化することができました 👍 

http://0.0.0.0:3000/

<img width="1233" alt="スクリーンショット 2021-12-02 21 15 41" src="https://user-images.githubusercontent.com/17666221/144420452-414926f2-b3e9-4cf5-af46-9bc3a923fdca.png">
